### ISSUE TITLE
Incorrect song downloading

### ISSUE THREAD

**Issue by shakdwipeea** [shreyans4nahata/WhiteWalker#6]
I searched for Faded . It downloaded the third song from the youtube listing . Have a look at [youtube api](https://developers.google.com/youtube/v3/guides/implementation/search) maybe this can make it more reliable.

**Comment by shreyans4nahata** [comment]
@shakdwipeea  It is because of [this](https://github.com/shreyans4nahata/WhiteWalker/blob/master/mytest/polls/views.py#L65).
This was done to ensure download of only the song and not the official video ; as the official video usually   starts with something other than the music itself, and the converted audio of that video was not a proper song.

**Comment by shakdwipeea** [comment]
@shreyans4nahata I tried the url with youtube-dl from cli that worked. So is the problem in the wrong url?

**Comment by shreyans4nahata** [comment]
@shakdwipeea  my bad! the earlier link pointed you to the line no.before the commit. 
Check [this line](https://github.com/shreyans4nahata/WhiteWalker/blob/master/mytest/polls/views.py#L59) out.

Don't think it is a flaw now as this is done intentionally.
